package models.enums;

public enum ChipFlavor {
    FIRST_LAYS_CLASSIC,
    SECOND_DORITOS_NACHO_CHEESE,
    THIRD_PRINGLES_ORIGINAL,
    FOURTH_RUFFLES_SOUR_CREAM_ONION,
    FIFTH_CHEETOS_CRUNCHY,
    SIXTH_KETTLE_SEA_SALT,
    SEVENTH_TOSTITOS_SCOOPS,
    EIGHTH_CAPE_COD_SEA_SALT,
    NINTH_TAKIS_FUEGO,
    TENTH_SUNCHIPS_HARVEST_CHEDDAR;
}
